// src/constants/subjects.js
export const availableSubjects = [
  { id: 1, name: 'Mathematics', icon: '📐', color: '#3b82f6', bgColor: '#eff6ff', description: 'Algebra, Calculus, Geometry' },
  { id: 2, name: 'Physical Science', icon: '⚛️', color: '#10b981', bgColor: '#f0fdf4', description: 'Physics & Chemistry' },
  { id: 3, name: 'English', icon: '📝', color: '#f59e0b', bgColor: '#fffbeb', description: 'Literature & Language' },
  { id: 4, name: 'Mathematical Literacy', icon: '📊', color: '#8b5cf6', bgColor: '#f5f3ff', description: 'Practical Mathematics' },
  { id: 5, name: 'Life Sciences', icon: '🧬', color: '#ec4899', bgColor: '#fdf2f8', description: 'Biology & Life Processes' },
  { id: 6, name: 'Geography', icon: '🌍', color: '#14b8a6', bgColor: '#f0fdfa', description: 'Physical & Human Geography' },
  { id: 7, name: 'History', icon: '📜', color: '#f97316', bgColor: '#fff7ed', description: 'World & South African History' },
  { id: 8, name: 'Accounting', icon: '💰', color: '#6b7280', bgColor: '#f3f4f6', description: 'Financial Accounting' },
  { id: 9, name: 'Business Studies', icon: '💼', color: '#84cc16', bgColor: '#f7fee7', description: 'Business Management' },
  { id: 10, name: 'Economics', icon: '📈', color: '#06b6d4', bgColor: '#ecfeff', description: 'Micro & Macroeconomics' },
  { id: 11, name: 'Agricultural Sciences', icon: '🌾', color: '#2ecc71', bgColor: '#e8f8f5', description: 'Farming, Crop Production, Animal Husbandry' },
  { id: 12, name: 'Tourism', icon: '✈️', color: '#e67e22', bgColor: '#fef5e7', description: 'Travel, Hospitality, Tourism Management' },
  { id: 13, name: 'isiZulu Home Language', icon: '🗣️', color: '#3498db', bgColor: '#ebf5ff', description: 'isiZulu Language & Literature' },
  { id: 14, name: 'isiXhosa Home Language', icon: '🗣️', color: '#9b59b6', bgColor: '#f3e8ff', description: 'isiXhosa Language & Literature' },
  { id: 15, name: 'siSwati Home Language', icon: '🗣️', color: '#1abc9c', bgColor: '#e8f8f5', description: 'siSwati Language & Literature' },
  { id: 16, name: 'isiNdebele Home Language', icon: '🗣️', color: '#e74c3c', bgColor: '#fef2f0', description: 'isiNdebele Language & Literature' },
  { id: 17, name: 'Sesotho Home Language', icon: '🗣️', color: '#f39c12', bgColor: '#fef9e7', description: 'Sesotho Language & Literature' },
  { id: 18, name: 'Setswana Home Language', icon: '🗣️', color: '#16a085', bgColor: '#e8f8f5', description: 'Setswana Language & Literature' },
  { id: 19, name: 'Sepedi Home Language', icon: '🗣️', color: '#d35400', bgColor: '#fef5e7', description: 'Sepedi (Northern Sotho) Language & Literature' },
  { id: 20, name: 'Tshivenda Home Language', icon: '🗣️', color: '#27ae60', bgColor: '#e8f8f5', description: 'Tshivenda Language & Literature' },
  { id: 21, name: 'Xitsonga Home Language', icon: '🗣️', color: '#2980b9', bgColor: '#ebf5ff', description: 'Xitsonga Language & Literature' },
];